# Generated by Django 3.2.18 on 2023-08-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
