# Generated by Django 3.2.18 on 2023-08-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_orderedcake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedCake',
        ),
    ]
