# Generated by Django 3.2.18 on 2023-08-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_orderedcakes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedcakes',
            name='image',
            field=models.ImageField(upload_to='Ordered-cakeimages/'),
        ),
    ]
