# Generated by Django 3.2.18 on 2023-08-27 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_orderedcakes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='url',
        ),
        migrations.RemoveField(
            model_name='orderedcakes',
            name='url',
        ),
    ]
